import os


POLONIEX_KEY = os.getenv('SJGHBOT_POLONIEX_KEY')
POLONIEX_SECRET = os.getenv('SJGHBOT_POLONIEX_SECRET')
TWITTER_CONSUMER_KEY = os.getenv('SJGHBOT_TWITTER_CONSUMER_KEY')
TWITTER_CONSUMER_SECRET = os.getenv('SJGHBOT_TWITTER_CONSUMER_SECRET')
TWITTER_ACCESS_TOKEN_KEY = os.getenv(
    'SJGHBOT_TWITTER_ACCESS_TOKEN_KEY'
)
TWITTER_ACCESS_TOKEN_SECRET = os.getenv(
    'SJGHBOT_TWITTER_ACCESS_TOKEN_SECRET'
)
